module.exports = {
  articulos: [
    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234206/ecommerce/trdzfr02bpu0rxdqkfaw.webp",
      name: "MOTHER ASUS (AM5) ROG STRIX B650E-E GAMING WFI",
      brand: "Asus",
      detail: [
        "AMD Socket AM5 for AMD Ryzen 7000 Series Desktop Processors",
        "Total supports 4 x M.2 slots and 4 x SATA 6Gb/s ports",
        "ROG SupremeFX 7.1 Surround Sound High Definition Audio CODEC ALC4080",
        "4x DIMM Slots, DDR5 6400MHz, PCIe Gen 5, 4x SATA 6Gb/s connectors, 4xM.2 Slot, 2.5GB LAN",
        "Graphics: 1 x DisplayPort* 1 x HDMI® port",
        "Expansion Slots AMD Ryzen™ 7000 Series Desktop Processors*",
      ],
      price: 217.453,
      category: "Motherboard",
      stock: 0,
      delete: false,
    },
    {
      //: 2,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230391/ecommerce/drzvjayerw4j9h3adtke.jpg",
      name: "ASUS Prime Z390-A Motherboard",
      brand: "Asus",
      detail: [
        "Intel LGA 1151 socket",
        "DDR4 memory compatibility",
        "Dual M.2, Gigabit LAN, and USB 3.1 Gen 2",
        "OptiMem II technology for stability and improved DDR4 overclocking",
        "Fan Xpert 4 for advanced fan and liqu// cooling controls",
      ],
      price: 189.99,
      category: "Motherboard",
      stock: 5,
      delete: false,
    },
    {
      //: 3,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230419/ecommerce/irdhszyturwcrjwkcvse.png",
      name: "Gigabyte B450M DS3H",
      brand: "Gigabyte",
      detail: [
        "AMD Ryzen AM4 socket",
        "Dual Channel DDR4, 4 DIMMs",
        "PCIe Gen3 M.2 NVMe with thermal guard",
        "High-quality Audio Capacitors and Audio Noise Guard with LED Trace Path Lighting",
        "RGB Fusion supports RGB LED strips in 7 colors",
        "Smart Fan 5 with Fan Stop for silent cooling",
      ],
      price: 72.99,
      category: "Motherboard",
      stock: 10,
      delete: false,
    },
    {
      //: 4,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230434/ecommerce/nkpx1dmchavchbvi5nss.jpg",
      name: "ASRock H310CM-HDV LGA1151/Intel H310/DDR4/SATA3&USB3.1",
      brand: "ASRock",
      detail: [
        "Intel LGA 1151 socket",
        "DDR4 memory compatibility",
        "M.2 for SSDs",
        "Realtek Gigabit LAN",
        "5X Protection II for hardware-level safeguards",
      ],
      price: 68.99,
      category: "Motherboard",
      stock: 8,
      delete: false,
    },
    {
      //: 5,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230448/ecommerce/gc8ube8gmdijzjbqp4vj.jpg",
      name: "MSI MPG Z590 Gaming Edge WiFi ATX Gaming Motherboard",
      brand: "MSI",
      detail: [
        "Supports 11th and 10th Gen Intel Core/Pentium/Celeron processors",
        "DDR4 Memory, up to 5333 MHz",
        "Lightning-fast experience: PCIe 4.0, Lightning Gen 4 M.2",
        "Wi-Fi 6E ready: 6GHz band prov//es the next level of Wi-Fi",
      ],
      price: 68.99,
      category: "Motherboard",
      stock: 10,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230465/ecommerce/os0nue4dxtjqsyiwcosf.jpg",
      name: "ASUS ROG MAXIMUS XIII HERO",
      brand: "Asus",
      detail: [
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-5333 MHz (OC)",
        "2.5 Gbps Ethernet, Wi-Fi 6E, Bluetooth 5.2",
        "USB 3.2 Gen 2x2 front panel connector, Thunderbolt 4 support",
        "5-Way Optimization, AI Overclocking, and AI Cooling",
        "Integrated I/O shield and Aura Sync RGB lighting",
      ],
      price: 599.99,
      category: "Motherboard",
      stock: 5,
      delete: false,
    },
    {
      //: 7,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230483/ecommerce/sf6lp6ez9loab5ijfyir.jpg",
      name: "GIGABYTE AORUS X570 MASTER",
      brand: "Gigabyte",
      detail: [
        "AMD X570 Chipset",
        "AMD AM4 Socket",
        "4 x DIMM DDR4-4400 MHz (OC)",
        "Intel WiFi 6 802.11ax, Bluetooth 5.0",
        "2.5 GbE LAN, ALC1220-VB Audio Codec, ESS SABRE HiFi 9118 DAC",
        "12+2 Phases IR Digital VRM Solution with PowIRstage",
      ],
      price: 359.99,
      category: "Motherboard",
      stock: 2,
      delete: false,
    },
    {
      //: 8,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230513/ecommerce/sgaxpded1k6jcvebzld5.jpg",
      name: "ASROCK B560M STEEL LEGEND",
      brand: "ASRock",
      detail: [
        "Intel B560 Chipset",
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-5000 MHz (OC)",
        "2.5 GbE LAN, Intel Wi-Fi 6E",
        "USB 3.2 Gen 2x2 Type-C, Thunderbolt 4 support",
        "Steel Legend Armor and RGB Lighting",
      ],
      price: 144.99,
      category: "Motherboard",
      stock: 8,
      delete: false,
    },

    {
      //: 9,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230526/ecommerce/kk4qhsr0d1c2jk6lcjcx.png",
      name: "ASUS ROG STRIX Z490-E GAMING",
      brand: "Asus",
      detail: [
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-4600 MHz (OC)",
        "2.5 Gbps Ethernet, Wi-Fi 6, Bluetooth 5.1",
        "USB 3.2 Gen 2x2 Type-C, Thunderbolt 3 support",
        "ROG SupremeFX ALC1220A Audio Codec",
        "Pre-mounted I/O shield and Aura Sync RGB lighting",
      ],
      price: 349.99,
      category: "Motherboard",
      stock: 3,
      delete: false,
    },
    {
      //: 10,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230543/ecommerce/sqrpwnlpjpupb5swvufo.jpg",
      name: "GIGABYTE Z590 AORUS MASTER",
      brand: "Gigabyte",
      detail: [
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-5400 MHz (OC)",
        "Intel 2.5 GbE LAN, Wi-Fi 6E, Bluetooth 5.2",
        "USB 3.2 Gen 2x2 Type-C, Thunderbolt 4 support",
        "ALC1220-VB Audio Codec, ESS SABRE HiFi 9118 DAC",
        "Advanced Thermal Design with Fins-Array II, Direct Touch Heatpipe II, and Nanocarbon Coating",
      ],
      price: 549.99,
      category: "Motherboard",
      stock: 4,
      delete: false,
    },

    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230559/ecommerce/psoho7d74wkumvxy6z9q.jpg",
      name: "LG 27'27GL650F G",
      brand: "LG",
      detail: [
        "G-Sync Compatible certificado por NV//IA",
        "Tamaño (pulgada) 27 pulgadasTalla (cm): 68.5cm",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 5 ms (GtG a mayor veloc//ad), 1 ms MBR",
        "Tratamiento de superficies: Antirreflejo, 25% 3H.",
      ],
      price: 19.99,
      category: "Monitores",
      stock: 4,
      delete: false,
    },
    {
      //: 2,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230577/ecommerce/ywqbnw0myssvoxprshwf.jpg",
      name: "ViewSonic VX2768-2KPC-MHD",
      brand: "ViewSonic",
      detail: [
        "Tamaño de pantalla: 27 pulgadas (27 pulgadas / 68,47 cm visible)",
        "Resolución: WQHD (2560 x 1440)",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "Tecnología AMD FreeSync",
      ],
      price: 279.99,
      category: "Monitores",
      stock: 6,
      delete: false,
    },
    {
      //: 3,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230594/ecommerce/zbr9ji47aev2jpx5cwfg.jpg",
      name: "Dell S2719DGF",
      brand: "Dell",
      detail: [
        "Tamaño de pantalla: 27 pulgadas",
        "Resolución: QHD (2560 x 1440)",
        "Tipo de panel: TN",
        "Tiempo de respuesta: 1 ms",
        "Frecuencia de actualización: 155Hz",
        "Tecnología AMD FreeSync 2 HDR",
      ],
      price: 319.99,
      category: "Monitores",
      stock: 2,
      delete: false,
    },
    {
      //: 4,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230609/ecommerce/yzhzoj4uzjjabmbkxnjs.jpg",
      name: "ASUS TUF Gaming VG249Q",
      brand: "ASUS",
      detail: [
        "Tamaño (pulgada) 23,8 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "Altavoces estéreo integrados",
      ],
      price: 269.99,
      category: "Monitores",
      stock: 8,
      delete: false,
    },

    {
      //: 5,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230627/ecommerce/ivip4bv2zyir8duurm8m.jpg",
      name: "AOC 27G2",
      brand: "AOC",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "Altavoces estéreo integrados",
      ],
      price: 249.99,
      category: "Monitores",
      stock: 12,
      delete: false,
    },

    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230660/ecommerce/qigh8y97f8zng862vt4a.jpg",
      name: "Samsung C27F398",
      brand: "Samsung",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: VA",
        "Tiempo de respuesta: 4 ms (GtG)",
        "Frecuencia de actualización: 60Hz",
        "Curvatura de pantalla 1800R",
      ],
      price: 229.99,
      category: "Monitores",
      stock: 6,
      delete: false,
    },
    {
      //: 7,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230675/ecommerce/wdm9tl2xefweo8impb1x.jpg",
      name: "Dell Ultrasharp U2415",
      brand: "Dell",
      detail: [
        "Tamaño (pulgada) 24 pulgadas",
        "Resolución: 1920 x 1200",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 6 ms (GtG)",
        "Frecuencia de actualización: 60Hz",
        "Relación de aspecto 16:10",
      ],
      price: 249.99,
      category: "Monitores",
      stock: 10,
      delete: false,
    },

    {
      //: 8,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230689/ecommerce/rd7rikuaaipik4yyw4gd.jpg",
      name: "Acer Nitro XV272U",
      brand: "Acer",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 2560 x 1440",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (VRB)",
        "Frecuencia de actualización: 144Hz",
        "HDR10",
      ],
      price: 399.99,
      category: "Monitores",
      stock: 5,
      delete: false,
    },

    {
      //: 9,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230702/ecommerce/fqghh5nqopnizintrpc1.jpg",
      name: "HP EliteDisplay E273",
      brand: "HP",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 5 ms (GtG)",
        "Frecuencia de actualización: 60Hz",
        "Inclinación, pivote, rotación y ajuste de altura",
      ],
      price: 279.99,
      category: "Monitores",
      stock: 7,
      delete: false,
    },

    {
      //: 10,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683230718/ecommerce/gya1pndmrlgablo4cz0f.png",
      name: "ViewSonic XG2405",
      brand: "ViewSonic",
      detail: [
        "Tamaño (pulgada) 24 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "FreeSync Premium",
      ],
      price: 189.99,
      category: "Monitores",
      stock: 9,
      delete: false,
    },

    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234367/ecommerce/auriculares-gamer-logitech-g335-white-jack-35-mm-pcps4-xbox_smtnrl.png",
      name: "AURICULAR GAMER LOGITECH G335 WHITE",
      brand: "Logitech",
      detail: [
        "Longitud: 189 mm",
        "Ancho: 180 mm",
        "Profund//ad: 79 mm",
        "Peso: 240 g (inclu//o el cable)",
        "Microfono : Integrado, fijo. Con boton de muteo.Compatibil//ad : PC, Xbox, PlayStation, Nintendo Switch y dispositivos móviles con toma de audio de 3,5 mm",
        "Respuesta de frecuencia: 100 Hz - 10 KHz",
      ],
      price: 189.99,
      category: "Auriculares",
      stock: 9,
      delete: false,
    },
    {
      //: 2,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234403/ecommerce/643502-MLA46284051542_062021-F_eetrbz.jpg",
      name: "AURICULAR GAMER MSI IMMERS GH30 V2",
      brand: "MSI",
      detail: [
        "Longitud: 200 mm",
        "Ancho: 105 mm",
        "Profund//ad: 205 mm",
        "Peso: 240 g",
        "Microfono : Un//ireccional con cancelacion de ru//o, con boton de muteo.Compatibil//ad : PC, Xbox, PlayStation, Nintendo Switch y dispositivos móviles con toma de audio de 3,5 mm",
        "Respuesta de frecuencia: 20 Hz - 20 KHz",
      ],
      price: 69.99,
      category: "Auriculares",
      stock: 15,
      delete: false,
    },
    {
      //: 3,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234423/ecommerce/18921-2_dnu6lx.jpg",
      name: "AURICULAR GAMER REDRAGON LAMIA H320",
      brand: "Redragon",
      detail: [
        "Longitud: 180 mm",
        "Ancho: 105 mm",
        "Profund//ad: 200 mm",
        "Peso: 290 g",
        "Microfono : Omn//ireccional con cancelacion de ru//o, con boton de muteo.Compatibil//ad : PC, Xbox, PlayStation, Nintendo Switch y dispositivos móviles con toma de audio de 3,5 mm",
        "Respuesta de frecuencia: 20 Hz - 20 KHz",
      ],
      price: 49.99,
      category: "Auriculares",
      stock: 5,
      delete: false,
    },
    {
      //: 4,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234433/ecommerce/D_NQ_NP_713953-MLA29337198688_022019-O_pvy60e.jpg",
      name: "LOGITECH G633 ARTEMIS SPECTRUM",
      brand: "Logitech",
      detail: [
        "Longitud: 182 mm",
        "Ancho: 81.7 mm",
        "Profund//ad: 182 mm",
        "Peso: 374 g",
        "Microfono: Micrófono con brazo ajustable y cancelación de ru//o",
        "Respuesta de frecuencia: 20 Hz - 20 KHz",
      ],
      price: 149.99,
      category: "Auriculares",
      stock: 8,
      delete: false,
    },
    {
      //: 5,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234475/ecommerce/D_NQ_NP_650755-MLA40807371233_022020-O_jnfipr.webp",
      name: "RAZER KRAKEN X",
      brand: "Razer",
      detail: [
        "Longitud: 205 mm",
        "Ancho: 195 mm",
        "Profund//ad: 88 mm",
        "Peso: 250 g",
        "Microfono: Micrófono cardio//e un//ireccional con cancelación de ru//o",
        "Respuesta de frecuencia: 12 Hz - 28 KHz",
      ],
      price: 49.99,
      category: "Auriculares",
      stock: 5,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234490/ecommerce/AUG118-jpg_wnbv3r.webp",
      name: "RAZER KRAKEN KITTY",
      brand: "Razer",
      detail: [
        "Longitud: 205 mm",
        "Ancho: 195 mm",
        "Profund//ad: 88 mm",
        "Peso: 250 g",
        "Microfono: Micrófono cardio//e un//ireccional con cancelación de ru//o",
        "Respuesta de frecuencia: 12 Hz - 28 KHz",
      ],
      price: 49.99,
      category: "Auriculares",
      stock: 5,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234501/ecommerce/616y3R63PcL_mv4ulk.jpg",
      name: "RAZER KRAKEN KITTY BLACK",
      brand: "Razer",
      detail: [
        "Longitud: 205 mm",
        "Ancho: 195 mm",
        "Profund//ad: 88 mm",
        "Peso: 250 g",
        "Microfono: Micrófono cardio//e un//ireccional con cancelación de ru//o",
        "Respuesta de frecuencia: 12 Hz - 28 KHz",
      ],
      price: 49.99,
      category: "Auriculares",
      stock: 5,
      delete: false,
    },
    {
      //: 7,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234513/ecommerce/auriculares-logitech-g-pro-x-gaming-981000817-0_l0kuxu.jpg",
      name: "LOGITECH G PRO X GAMING",
      brand: "Logitech",
      detail: [
        "Longitud: 180 mm",
        "Ancho: 105 mm",
        "Profund//ad: 200 mm",
        "Peso: 290 g",
        "Microfono: Micrófono omn//ireccional con cancelación de ru//o y botón de mute",
        "Respuesta de frecuencia: 20 Hz - 20 KHz",
      ],
      price: 49.99,
      category: "Auriculares",
      stock: 8,
      delete: false,
    },
    {
      //: 8,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234523/ecommerce/auriculares-razer-kraken-pro-v2-verde_f52edw.jpg",
      name: "RAZER KRAKEN ULTIMATE GREEN",
      brand: "Razer",
      detail: [
        "Longitud: 190 mm",
        "Ancho: 104.3 mm",
        "Profund//ad: 197.5 mm",
        "Peso: 390 g",
        "Microfono: Micrófono cardio//e un//ireccional con cancelación de ru//o activa",
        "Respuesta de frecuencia: 20 Hz - 20 KHz",
      ],
      price: 129.99,
      category: "Auriculares",
      stock: 10,
      delete: false,
    },
    {
      //: 9,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683291848/1019-producto-auricular-hyperx-cloud-ii-wireless-1-3068_xk7mng.jpg",
      name: "HYPERX CLOUD II",
      brand: "HyperX",
      detail: [
        "Longitud: 100 mm",
        "Ancho: 161 mm",
        "Profund//ad: 110 mm",
        "Peso: 320 g",
        "Microfono: Micrófono con cancelación de ru//o y control de volumen en línea",
        "Respuesta de frecuencia: 15 Hz - 25 KHz",
      ],
      price: 99.99,
      category: "Auriculares",
      stock: 7,
      delete: false,
    },
    {
      //: 10,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234543/ecommerce/6285956_rd_aviyfr.jpg",
      name: "STEELSERIES ARCTIS 7",
      brand: "SteelSeries",
      detail: [
        "Longitud: 193 mm",
        "Ancho: 100 mm",
        "Profund//ad: 205 mm",
        "Peso: 352 g",
        "Microfono: Micrófono b//ireccional con cancelación de ru//o",
        "Respuesta de frecuencia: 20 Hz - 20 KHz",
      ],
      price: 149.99,
      category: "Auriculares",
      stock: 9,
      delete: false,
    },

    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683292233/D_NQ_NP_964964-MLA32721999086_102019-O_fvz3ze.webp",
      name: "TECLADO CORSAIR K55 RGB",
      brand: "Corsair",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: Rubber Dome",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Membrana",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Español España",
      ],
      price: 149.99,
      category: "Teclados",
      stock: 9,
      delete: false,
    },
    {
      //: 2,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234565/ecommerce/D_NQ_NP_902606-MLA43542876076_092020-O_jmotnv.jpg",
      name: "Logitech G Pro X",
      brand: "Logitech",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: GX Blue Clicky (intercambiables)",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Mecánica",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Inglés",
      ],
      price: 149.99,
      category: "Teclados",
      stock: 5,
      delete: false,
    },
    {
      //: 3,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234578/ecommerce/teclado-gamer-twolf-t16-negro-teclado-gamer-twolf-t16-negro_pstm89.jpg",
      name: "Wolf Pack Gaming TKL",
      brand: "Wolf Pack",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: Outemu Blue (mecánico)",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Mecánica",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Español España",
      ],
      price: 79.99,
      category: "Teclados",
      stock: 10,
      delete: false,
    },
    {
      //: 4,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234597/ecommerce/TECLADO-MEC-HYPERX-ALLOY-FPS-PRO-BLUE_barcyv.jpg",
      name: "TECLADO GAMER HYPERX ALLOY FPS PRO",
      brand: "HyperX",
      detail: [
        "Color de la retroiluminación: Rojo (sólo la tecla WASD y las flechas)",
        "Tipo de switch: Cherry MX Red (mecánico)",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Mecánica",
        "Es resistente a salpicaduras: No",
        "//ioma: Español España",
      ],
      price: 89.99,
      category: "Teclados",
      stock: 3,
      delete: false,
    },
    {
      //: 5,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234615/ecommerce/23-167-047-V17_nnf6pm.jpg",
      name: "MSI Vigor GK30 Combo",
      brand: "MSI",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: Membrana (con teclas ergonómicas)",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Membrana",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Español España",
      ],
      price: 59.99,
      category: "Teclados",
      stock: 8,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234796/ecommerce/119_224254939376_60_eehdm6.jpg",
      name: "TECLADO GAMER LOGITECH G 915",
      brand: "Logitech",
      detail: [
        "Tipo de switch: Mecánico GX Blue",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Teclas flotantes",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Inglés",
      ],
      price: 129.99,
      category: "Teclados",
      stock: 6,
      delete: false,
    },
    {
      //: 7,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234809/ecommerce/nb_teclado-gamer-razer-ornata-v2-spanish_ver_4f3257556d6f27d1e132d8b5f7acb3e1_zxtdvn.png",
      name: "TECLADO GAMER RAZER ORNATA V2",
      brand: "Razer",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: Mecánico-Membrana",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Teclas flotantes",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Inglés",
      ],
      price: 99.99,
      category: "Teclados",
      stock: 8,
      delete: false,
    },
    {
      //: 8,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234841/ecommerce/19665-0_zf2fin.jpg",
      name: "TECLADO GAMER RAZER CYNOSA CHROMA",
      brand: "Razer",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: Membrana",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Membrana",
        "Es resistente a salpicaduras: No",
        "//ioma: Español Latinoamérica",
      ],
      price: 79.99,
      category: "Teclados",
      stock: 12,
      delete: false,
    },
    {
      //: 9,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234862/ecommerce/61i2f6xbd1L._AC_UF894_1000_QL80__vsacsm.jpg",
      name: "TECLADO GAMER LOGITECH G610 ORION",
      brand: "Logitech",
      detail: [
        "Color de la retroiluminación: Rojo",
        "Tipo de switch: Mecánico",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Mecánica",
        "Es resistente a salpicaduras: No",
        "//ioma: Inglés",
      ],
      price: 89.99,
      category: "Teclados",
      stock: 8,
      delete: false,
    },
    {
      //: 10,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234873/ecommerce/935185-MLA46504064329_062021-F_ogldzw.jpg",
      name: "TECLADO GAMER REDRAGON YAMA K550 RGB",
      brand: "Redragon",
      detail: [
        "Color de la retroiluminación: RGB",
        "Tipo de switch: Mecánico",
        "Tipo de conector: USB 2.0",
        "Arquitectura: Mecánica",
        "Es resistente a salpicaduras: Sí",
        "//ioma: Español España",
      ],
      price: 109.99,
      category: "Teclados",
      stock: 5,
      delete: false,
    },
    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234893/ecommerce/mouse-logitech-g203-gaming-lightsync-white-910005794-0_a9tyzq.jpg",
      name: "MOUSE GAMER LOGITECH G203 WHITE",
      brand: "Logitech",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 8000 dpi",
        "Con cable: Sí",
        "Con luces: Sí",
        "Cant//ad de botones: 6",
        "Alcance máximo: 2.1 m",
      ],
      price: 109.99,
      category: "Teclados",
      stock: 5,
      delete: false,
    },
    {
      //: 2,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234904/ecommerce/379caa_h77ydt.jpg",
      name: "MOUSE GAMER REDRAGON COBRA M711-FPS RGB",
      brand: "Redragon",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 10000 dpi",
        "Con cable: Sí",
        "Con luces: Sí",
        "Cant//ad de botones: 8",
        "Alcance máximo: 1.8 m",
      ],
      price: 59.99,
      category: "Mouses",
      stock: 7,
      delete: false,
    },
    {
      //: 3,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234913/ecommerce/hyperx-haste-wireless-wt-4p5d8aa_1669841762_original_h5x2vl.jpg",
      name: "MOUSE GAMER HYPERX PULSEFIRE HASTE WHITE",
      brand: "HyperX",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 16000 dpi",
        "Con cable: Sí",
        "Con luces: No",
        "Cant//ad de botones: 6",
        "Alcance máximo: 1.8 m",
      ],
      price: 79.99,
      category: "Mouses",
      stock: 3,
      delete: false,
    },
    {
      //: 4,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234924/ecommerce/61nKxSAAVFL._AC_SX425__a6yrub.jpg",
      name: "MOUSE GAMER HYPERX PULSEFIRE HASTE BLACK",
      brand: "HyperX",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 16000 dpi",
        "Con cable: Sí",
        "Con luces: No",
        "Cant//ad de botones: 6",
        "Alcance máximo: 1.8 m",
      ],
      price: 79.99,
      category: "Mouses",
      stock: 3,
      delete: false,
    },
    {
      //: 5,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234938/ecommerce/D_NQ_NP_978923-MLA32159134266_092019-O_zrayxq.jpg",
      name: "MOUSE GAMER LOGITECH G402 HYPERION FURY",
      brand: "Logitech",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 4000 dpi",
        "Con cable: Sí",
        "Con luces: Sí",
        "Cant//ad de botones: 8",
        "Alcance máximo: 2 m",
      ],
      price: 79.99,
      category: "Mouses",
      stock: 7,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234953/ecommerce/D_NQ_NP_686894-MLA31022953654_062019-O_mtni3m.jpg",
      name: "MOUSE GAMER RAZER DEATHADDER ESSENTIAL",
      brand: "Razer",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 16000 dpi",
        "Con cable: Sí",
        "Con luces: Sí",
        "Cant//ad de botones: 5",
        "Alcance máximo: 1.8 m",
      ],
      price: 89.99,
      category: "Mouses",
      stock: 4,
      delete: false,
    },
    {
      //: 7,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234968/ecommerce/D_NQ_NP_938598-MLA40436755950_012020-O_phf44a.jpg",
      name: "MOUSE GAMER RAZER BASILISK X HYPERSPEED",
      brand: "Razer",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 16000 dpi",
        "Con cable: No",
        "Con luces: Sí",
        "Cant//ad de botones: 6",
        "Alcance máximo: 10 m",
      ],
      price: 139.99,
      category: "Mouses",
      stock: 3,
      delete: false,
    },
    {
      //: 8,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234979/ecommerce/5f2abe775d9d2_xhzaqh.jpg",
      name: "MOUSE GAMER HP OMEN 400",
      brand: "HP",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 5000 dpi",
        "Con cable: Sí",
        "Con luces: Sí",
        "Cant//ad de botones: 6",
        "Alcance máximo: 1.8 m",
      ],
      price: 59.99,
      category: "Mouses",
      stock: 8,
      delete: false,
    },
    {
      //: 9,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683234995/ecommerce/Steelseries_20Rival_20310_20Black2-870x664_ikd0xx.jpg",
      name: "MOUSE GAMER STEELSERIES RIVAL 310",
      brand: "SteelSeries",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 12000 dpi",
        "Con cable: Sí",
        "Con luces: Sí",
        "Cant//ad de botones: 6",
        "Alcance máximo: N/A",
      ],
      price: 79.99,
      category: "Mouses",
      stock: 6,
      delete: false,
    },
    {
      //: 10,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235181/ecommerce/image_523_ibaipv.jpg",
      name: "MOUSE GAMER CORSAIR HARPOON RGB WIRELESS",
      brand: "Corsair",
      detail: [
        "Tipo de sensor: Óptico",
        "Resolución del sensor: 10000 dpi",
        "Con cable: No",
        "Con luces: Sí",
        "Cant//ad de botones: 6",
        "Alcance máximo: 10 m",
      ],
      price: 69.99,
      category: "Mouses",
      stock: 8,
      delete: false,
    },

    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235283/ecommerce/1585940629_amd_ryzen_3_3200g_am4_uxw3xk.jpg",
      name: "PROCESADOR AMD RYZEN 3 3200G AM4",
      brand: "AMD",
      detail: [
        "Línea: Ryzen 3",
        "Modelo: 3200G",
        "Accesorios inclu//os: Air cooler",
        "Arquitectura: x86-64",
        "Cant//ad de núcleos de CPU: 4",
        "Frecuencia mínima de reloj: 3.6 GHz",
      ],
      price: 69.99,
      category: "Procesadores",
      stock: 8,
      delete: false,
    },
    {
      //: 2,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683236673/ecommerce/61DYLoyNRWL._AC_UY218__bv6uxt.jpg",
      name: "AMD Ryzen 7 5800X",
      brand: "AMD",
      detail: [
        "Núcleos: 8",
        "Hilos: 16",
        "Veloc//ad base: 3.8 GHz",
        "Veloc//ad turbo: 4.7 GHz",
        "Cache: 36MB",
        "Socket: AM4",
        "Consumo energético: 105W",
        "Tecnología de fabricación: 7nm",
      ],
      price: 419.99,
      category: "Procesadores",
      stock: 10,
      delete: false,
    },
    {
      //: 3,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235304/ecommerce/micro-intel-core-i9-11900k-8core-16m-35ghz-1200-1_noucgd.jpg",
      name: "Intel Core i9-11900K",
      brand: "Intel",
      detail: [
        "Núcleos: 8",
        "Hilos: 16",
        "Veloc//ad base: 3.5 GHz",
        "Veloc//ad turbo: 5.3 GHz",
        "Cache: 16MB",
        "Socket: LGA1200",
        "Consumo energético: 125W",
        "Tecnología de fabricación: 14nm",
      ],
      price: 549.99,
      category: "Procesadores",
      stock: 8,
      delete: false,
    },

    {
      //: 4,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235323/ecommerce/Ryzen-9-Ventila_CC_81tor-ne_CC_81lku_CC_88li-1_gllqjj.jpg",
      name: "AMD Ryzen 9 5950X",
      brand: "AMD",
      detail: [
        "Núcleos: 16",
        "Hilos: 32",
        "Veloc//ad base: 3.4 GHz",
        "Veloc//ad turbo: 4.9 GHz",
        "Cache: 72MB",
        "Socket: AM4",
        "Consumo energético: 105W",
        "Tecnología de fabricación: 7nm",
      ],
      price: 999.99,
      category: "Procesadores",
      stock: 5,
      delete: false,
    },

    {
      //: 5,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235342/ecommerce/concepto-6326925_cqoqfn.jpg",
      name: "Intel Core i7-11700K",
      brand: "Intel",
      detail: [
        "Núcleos: 8",
        "Hilos: 16",
        "Veloc//ad base: 3.6 GHz",
        "Veloc//ad turbo: 5.0 GHz",
        "Cache: 16MB",
        "Socket: LGA1200",
        "Consumo energético: 125W",
        "Tecnología de fabricación: 14nm",
      ],
      price: 419.99,
      category: "Procesadores",
      stock: 6,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235351/ecommerce/micro-intel-core-i5-11600k-11-gen-0_mejnew.jpg",
      name: "Intel Core i5-11600K",
      brand: "Intel",
      detail: [
        "Núcleos: 6",
        "Hilos: 12",
        "Veloc//ad base: 3.9 GHz",
        "Veloc//ad turbo: 4.9 GHz",
        "Cache: 12MB",
        "Socket: LGA1200",
        "Consumo energético: 125W",
        "Tecnología de fabricación: 14nm",
      ],
      price: 279.99,
      category: "Procesadores",
      stock: 7,
      delete: false,
    },
    {
      //: 6,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235364/ecommerce/D_NQ_NP_622984-MLM52374360803_112022-O_a0hxgb.jpg",
      name: "AMD Ryzen 5 5600X",
      brand: "AMD",
      detail: [
        "Núcleos: 6",
        "Hilos: 12",
        "Veloc//ad base: 3.7 GHz",
        "Veloc//ad turbo: 4.6 GHz",
        "Cache: 35MB",
        "Socket: AM4",
        "Consumo energético: 65W",
        "Tecnología de fabricación: 7nm",
      ],
      price: 299.99,
      category: "Procesadores",
      stock: 15,
      delete: false,
    },
    {
      //: 7,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235379/ecommerce/microprocesador-intel-corei3-10100-10ma_gen_yzgphv.png",
      name: "Intel Core i3-10100",
      brand: "Intel",
      detail: [
        "Núcleos: 4",
        "Hilos: 8",
        "Veloc//ad base: 3.6 GHz",
        "Veloc//ad turbo: 4.3 GHz",
        "Cache: 6MB",
        "Socket: LGA1200",
        "Consumo energético: 65W",
        "Tecnología de fabricación: 14nm",
      ],
      price: 129.99,
      category: "Procesadores",
      stock: 20,
      delete: false,
    },
    {
      //: 8,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235388/ecommerce/3960X_suopd3.png",
      name: "AMD Ryzen Threadripper 3990X",
      brand: "AMD",
      detail: [
        "Núcleos: 64",
        "Hilos: 128",
        "Veloc//ad base: 2.9 GHz",
        "Veloc//ad turbo: 4.3 GHz",
        "Cache: 288MB",
        "Socket: sTRX4",
        "Consumo energético: 280W",
        "Tecnología de fabricación: 7nm",
      ],
      price: 3999.99,
      category: "Procesadores",
      stock: 2,
      delete: false,
    },
    {
      //: 9,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683235401/ecommerce/concepto-10608112_m9zs7x.jpg",
      name: "AMD Ryzen 7 7700",
      brand: "AMD",
      detail: [
        "Núcleos: 64",
        "Hilos: 128",
        "Veloc//ad base: 2.9 GHz",
        "Veloc//ad turbo: 4.3 GHz",
        "Cache: 288MB",
        "Socket: sTRX4",
        "Consumo energético: 280W",
        "Tecnología de fabricación: 7nm",
      ],
      price: 3999.99,
      category: "Procesadores",
      stock: 2,
      delete: false,
    },
    {
      //: 10,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237405/ecommerce/procesador-amd-ryzen-9-7950x-socket-am5_zm3uzi.jpg",
      name: "AMD Ryzen 9 7900X3D",
      brand: "AMD",
      detail: [
        "Núcleos: 64",
        "Hilos: 128",
        "Veloc//ad base: 2.9 GHz",
        "Veloc//ad turbo: 4.3 GHz",
        "Cache: 288MB",
        "Socket: sTRX4",
        "Consumo energético: 280W",
        "Tecnología de fabricación: 7nm",
      ],
      price: 3999.99,
      category: "Procesadores",
      stock: 2,
      delete: false,
    },
    {
      //: 1,
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237425/ecommerce/1_zdgwqu.jpg",
      name: "KINGSTON FURY BEAST RGB 8GB",
      brand: "Kingston",
      detail: [
        "Módulos de memoria: 1 x 8 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 3999.99,
      category: "Procesadores",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237444/ecommerce/274_14-02-2023-01-02-01-memoria-ram-corsair-8gb-vengance-rgb-pro-2_wgqsga.jpg",
      name: "Corsair Vengeance RGB Pro DDR4 8GB 3200MHz",
      brand: "Corsair",
      detail: [
        "Módulos de memoria: 1 x 8 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 4499.0,
      category: "Memorias RAM",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237461/ecommerce/1_wiofwr.jpg",
      name: "KINGSTON FURY BEAST RGB 16GB",
      brand: "Kingston",
      detail: [
        "Módulos de memoria: 1 x 16 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 3799.0,
      category: "Memorias RAM",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237479/ecommerce/6eab90f11017678e3736046065533eb6-20181018134209_csmhv6.jpg",
      name: "TeamGroup Delta RGB DDR4 8GB 3200MHz",
      brand: "TeamGroup",
      detail: [
        "Módulos de memoria: 1 x 8 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 3199.0,
      category: "Memorias RAM",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237479/ecommerce/6eab90f11017678e3736046065533eb6-20181018134209_csmhv6.jpg",
      name: "TeamGroup Delta RGB DDR4 16GB 3200MHz",
      brand: "TeamGroup",
      detail: [
        "Módulos de memoria: 1 x 16 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 3199.0,
      category: "Memorias RAM",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237510/ecommerce/274_14-02-2023-01-02-01-memoria-ram-corsair-8gb-vengance-rgb-pro-2_fdlgzn.jpg",
      name: "Corsair Vengeance RGB Pro DDR4 16GB 3200MHz",
      brand: "Corsair",
      detail: [
        "Módulos de memoria: 1 x 16 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 4499.0,
      category: "Memorias RAM",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237528/ecommerce/MEM1108_x40a2s.bmp",
      name: "G.Skill Trident Z RGB 16GB (2x8GB) DDR4 3200MHz C16",
      brand: "G.Skill",
      detail: [
        "Módulos de memoria: 2 x 8 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 8399.99,
      category: "Memoria RAM",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237549/ecommerce/memoria-16gb-2x8-ddr4-3200-gskill-trident-z-rgb-neo-1_adkbxz.jpg",
      name: "G.Skill Trident Z RGB 8GB DDR4 3200MHz C16",
      brand: "G.Skill",
      detail: [
        "Módulos de memoria: 1 x 8 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 8399.99,
      category: "Memoria RAM",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237549/ecommerce/memoria-16gb-2x8-ddr4-3200-gskill-trident-z-rgb-neo-1_adkbxz.jpg",
      name: "G.Skill Trident Z RGB 16GB DDR4 3200MHz C16",
      brand: "G.Skill",
      detail: [
        "Módulos de memoria: 1 x 16 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 8399.99,
      category: "Memoria RAM",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237688/ecommerce/1605-patriot-viper-steel-rgb-ddr4-3600mhz-16gb-cl19_rmawyg.webp",
      name: "Patriot Viper Steel RGB DDR4 16GB 3200MHz",
      brand: "Patriot",
      detail: [
        "Módulos de memoria: 1 x 16 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 7899.99,
      category: "Memoria RAM",
      stock: 7,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237688/ecommerce/1605-patriot-viper-steel-rgb-ddr4-3600mhz-16gb-cl19_rmawyg.webp",
      name: "Patriot Viper Steel RGB DDR4 8GB 3200MHz",
      brand: "Patriot",
      detail: [
        "Módulos de memoria: 1 x 8 GB",
        "Aplicación: Computadoras de escritorio",
        "Tecnología: DDR4 SDRAM",
        "Velocidad: 3200 MHz",
        "Tasa de transferencia: 25600 MB/s",
        "RGB: Si",
      ],
      price: 7899.99,
      category: "Memoria RAM",
      stock: 7,
      delete: false,
    },
    {
      //1
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237792/ecommerce/gabinete-corsair-icue-4000x-rgb-vidrio-templado-midtower-at-0_l8xgp6.jpg",
      name: "PC GAMER AMD RYZEN 7 5800X 3080 32GB SSD 512 750W 4000X",
      brand: "PC GAMER",
      detail: [
        "1 | PROCESADOR AMD RYZEN 7 5800X",
        "1 | WATER COOLER 240MM ARGB COOLERMASTER",
        "1 | DDR4 CORSAIR RGB 32GB (16GBX2) 3200MHZ",
        "1 | MOTHER GAMER B550",
        "1 | PLACA DE VIDEO RTX 3080",
        "1 | DISCO SSD 512 GB",
        "1 | GABINETE CORSAIR 4000X ICUE",
        "1 | FUENTE AEROCOOL 750W GOLD FULL MODULAR",
      ],
      price: 7899.99,
      category: "Equipos armados",
      stock: 7,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237803/ecommerce/Gabinete-Gamer-Noga-NG09_ekehgd.jpg",
      name: "PC GAMER AMD RYZEN 7 3700X GTX 3070 16GB SSD 512 750W",
      brand: "PC GAMER",
      detail: [
        "1 | PROCESADOR AMD RYZEN 7 3700X",
        "1 | WATER COOLER 120MM RGB COOLERMASTER",
        "1 | DDR4 CORSAIR RGB 16GB (8GBX2) 3200MHZ",
        "1 | MOTHER GAMER B450",
        "1 | PLACA DE VIDEO GTX 3070",
        "1 | DISCO SSD 512 GB",
        "1 | GABINETE THERMALTAKE V200 RGB",
      ],
      price: 4799.99,
      category: "Equipos armados",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237818/ecommerce/gabinete-pc-gamer-sentey-x10-rgb-acrilico-gaming-usb-30-sin-fuente_tu7mny.jpg",
      name: "PC GAMER AMD RYZEN 5 5600X GTX 1660 SUPER 16GB SSD 512 600W",
      brand: "PC GAMER",
      detail: [
        "1 | PROCESADOR AMD RYZEN 5 5600X",
        "1 | WATER COOLER 120MM RGB COOLERMASTER",
        "1 | DDR4 CORSAIR RGB 16GB (8GBX2) 3200MHZ",
        "1 | MOTHER GAMER B550",
        "1 | PLACA DE VIDEO GTX 1660 SUPER",
        "1 | DISCO SSD 512 GB",
        "1 | GABINETE THERMALTAKE H200",
      ],
      price: 3799.99,
      category: "Equipos armados",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237831/ecommerce/7493_1_pd2o2p.jpg",
      name: "PC GAMER MSI SEKHMET RYZEN 5 5600X 3060 16GB SSD 500 600W",
      brand: "MSI",
      detail: [
        "1 | PROCESADOR AMD RYZEN 5 5600X",
        "1 | WATER COOLER 120MM ARGB MSI",
        "1 | DDR4 AORUS RGB 16GB (8GBX2) 3200MHZ",
        "1 | MOTHER GAMER B550",
        "1 | PLACA DE VIDEO RTX 3060",
        "1 | DISCO SSD 500 GB",
        "1 | GABINETE MSI SEKHMET ARGB",
      ],
      price: 4999.99,
      category: "Equipos armados",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237841/ecommerce/1665606353766_zxuyaj.jpg",
      name: "PC GAMER INTEL CORE I7 10700F 3060 16GB SSD 512 600W 465X",
      brand: "PC GAMER",
      detail: [
        "1 | PROCESADOR INTEL CORE I7 10700F",
        "1 | WATER COOLER 240MM COOLERMASTER",
        "1 | DDR4 CORSAIR RGB 16GB (8GBX2) 3200MHZ",
        "1 | MOTHER GAMER B460",
        "1 | PLACA DE VIDEO RTX 3060",
        "1 | DISCO SSD 512 GB",
        "1 | GABINETE CORSAIR 465X ICUE",
      ],
      price: 5999.99,
      category: "Equipos armados",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683237792/ecommerce/gabinete-corsair-icue-4000x-rgb-vidrio-templado-midtower-at-0_l8xgp6.jpg",
      name: "PC GAMER AMD RYZEN 5 5600X 3070 16GB SSD 512 750W CV27Q",
      brand: "PC GAMER",
      detail: [
        "1 | PROCESADOR AMD RYZEN 5 5600X",
        "1 | WATER COOLER 240MM ARGB AORUS",
        "1 | DDR4 CORSAIR RGB 16GB (8GBX2) 3200MHZ",
        "1 | MOTHER GAMER B550",
        "1 | PLACA DE VIDEO RTX 3070",
        "1 | DISCO SSD 512 GB",
        "1 | GABINETE AORUS CV27Q ARGB",
      ],
      price: 6799.99,
      category: "Equipos armados",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238332/ecommerce/1151-8c0825a8ead191875915988811001898-640-0_nk99gu.jpg",
      name: "PC GAMER WOLFPACK HURRICANE I9-11900KF/RTX 3080TI/32GB/1TB SSD",
      brand: "PC GAMER",
      detail: [
        "Procesador: Intel Core i9-11900KF",
        "Refrigeración: Liquida",
        "Memoria RAM: 32 GB DDR4",
        "Placa Base: ASUS Z590",
        "Tarjeta gráfica: NVIDIA GeForce RTX 3080TI",
        "Almacenamiento: SSD 1 TB",
        "Caja: Lian-Li PC-O11 Dynamic Blanco",
      ],
      price: 4499.0,
      category: "Equipos armados",
      stock: 4,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238347/ecommerce/274_27-12-2022-03-12-05-gabinete-aureox-volans_ubxgcm.jpg",
      name: "PC GAMER MSI MAG INFINITE S3 11TK-618EU INTEL CORE I7-11700F/32GB/1TB SSD/RTX 3060TI",
      brand: "PC GAMER",
      detail: [
        "Procesador: Intel Core i7-11700F",
        "Refrigeración: Aire",
        "Memoria RAM: 32 GB DDR4",
        "Placa Base: MSI B560M",
        "Tarjeta gráfica: NVIDIA GeForce RTX 3060TI",
        "Almacenamiento: SSD 1 TB",
        "Caja: MSI MAG VAMPIRIC 010M",
      ],
      price: 1999.0,
      category: "Equipos armados",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238364/ecommerce/1665525906174_xidxfj.jpg",
      name: "PC GAMER EVOLUTION GAMING RYZEN 9 5950X/RTX 3090/64GB/1TB NVME SSD",
      brand: "PC GAMER",
      detail: [
        "Procesador: AMD Ryzen 9 5950X",
        "Refrigeración: Liquida",
        "Memoria RAM: 64 GB DDR4",
        "Placa Base: ASUS TUF GAMING X570",
        "Tarjeta gráfica: NVIDIA GeForce RTX 3090",
        "Almacenamiento: SSD 1 TB",
        "Caja: Lian-Li PC-O11 Dynamic Negro",
      ],
      price: 7299.0,
      category: "Equipos armados",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238381/ecommerce/993762-MLA53563874824_022023-F_ahpi4m.jpg",
      name: "PC Gamer WDC i5-10400F/16GB/1TB SSD/RTX 3060Ti 8GB",
      brand: "PC GAMER",
      detail: [
        "Procesador Intel Core i5-10400F (6 núcleos, 12 MB de caché, 2.9 GHz hasta 4.3 GHz)",
        "16 GB RAM DDR4",
        "1 TB SSD",
        "Tarjeta gráfica NVIDIA GeForce RTX 3060Ti 8GB GDDR6",
        "Conectividad: Ethernet LAN 10/100/1000, Wi-Fi 802.11ac, Bluetooth 5.0",
        "Caja ATX Corsair 275R Airflow",
        "Fuente de alimentación 750W 80 Plus Gold",
      ],
      price: 1529.0,
      category: "Equipos armados",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238394/ecommerce/618653-MLA52353077603_112022-F_vrzjzl.jpg",
      name: "PC Gaming Megaport Ryzen 5 3500X 6x 4.10GHz",
      brand: "PC GAMER",
      detail: [
        "Procesador AMD Ryzen 5 3500X (6 núcleos, 12 hilos, 4.1 GHz)",
        "16 GB RAM DDR4",
        "512 GB SSD",
        "Tarjeta gráfica NVIDIA GeForce GTX 1650 4GB GDDR5",
        "Conectividad: Ethernet LAN 10/100/1000, Wi-Fi 802.11ac, Bluetooth 5.0",
        "Caja Gaming RGB con vidrio templado",
        "Fuente de alimentación 500W",
      ],
      price: 969.0,
      category: "Equipos armados",
      stock: 5,
      delete: false,
    },
    {
      // 1
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238407/ecommerce/Untitled_p2nsca.jpg",
      name: "NOTEBOOK GIGABYTE 15.6 I7 12700H 16GB 1TB RTX3070TI W10H",
      brand: "Intel",
      detail: [
        "Procesador: Core I7 12700H",
        "Tarjeta de video: GeForce RTX 3070 TI 8Gb GDDR6",
        "Frecuencia: 4.70 GHz",
        "Memoria ram: 16GB (2X8GB)",
        "Almacenamiento: 1TB",
        "Resolución: 2560x1440 165HZ",
        "Tamaño: 15.6",
      ],
      price: 969.0,
      category: "Notebooks",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238567/ecommerce/notebook_dell_alienware_m15_r6_gaming_core_i7_11800h_256gb_ssd_8gb_15_6_165hz__rtx_3050_ti_k94f301_ybc1sv.jpg",
      name: "Notebook Dell Alienware m15 R6",
      brand: "Dell",
      detail: [
        "Procesador: Intel Core i7-11800H",
        "Tarjeta de video: NVIDIA GeForce RTX 3070 8GB GDDR6",
        "Frecuencia: 4.6 GHz",
        "Memoria ram: 16GB DDR4 3200MHz",
        "Almacenamiento: 512GB SSD PCIe M.2",
        "Resolución: 1920x1080 300Hz",
        "Tamaño: 15.6",
      ],
      price: 1999.99,
      category: "Notebooks",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238434/ecommerce/71zNU5UBINL._AC_SL1500__njed96.jpg",
      name: "Notebook ASUS ROG Zephyrus G14 GA401QM",
      brand: "ASUS",
      detail: [
        "Procesador: AMD Ryzen 9 5900HS",
        "Tarjeta de video: NVIDIA GeForce RTX 3060 6GB GDDR6",
        "Frecuencia: 4.6 GHz",
        "Memoria ram: 16GB DDR4 3200MHz",
        "Almacenamiento: 1TB SSD PCIe M.2",
        "Resolución: 2560x1440 120Hz",
        "Tamaño: 14",
      ],
      price: 1499.99,
      category: "Notebooks",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238587/ecommerce/71FeUtw_TPL._SL1500__okn9ch.jpg",
      name: "Notebook HP Pavilion Gaming 15-EC1023AX",
      brand: "HP",
      detail: [
        "Procesador: AMD Ryzen 5 5600H",
        "Tarjeta de video: NVIDIA GeForce GTX 1650 4GB GDDR6",
        "Frecuencia: 4.2 GHz",
        "Memoria ram: 8GB DDR4 3200MHz",
        "Almacenamiento: 512GB SSD PCIe NVMe M.2",
        "Resolución: 1920x1080 144Hz",
        "Tamaño: 15.6",
      ],
      price: 799.99,
      category: "Notebooks",
      stock: 7,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238603/ecommerce/MSI_2BGL75_2BLeopard_2B10SEK-040XES_dhnwla.jpg",
      name: "MSI GL65 9SD-266XES",
      brand: "MSI",
      detail: [
        "Procesador: Intel Core i7-9750H",
        "Tarjeta de video: NVIDIA GeForce GTX 1660 Ti 6GB",
        "Frecuencia: 2.6 GHz (hasta 4.5 GHz)",
        "Memoria ram: 16GB DDR4 (2666 MHz)",
        "Almacenamiento: SSD 512GB",
        "Resolución: Full HD 1920x1080 (120 Hz)",
        "Tamaño: 15.6",
      ],
      price: 1299.0,
      category: "Notebooks",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238620/ecommerce/41WDa2IOiYL._AC__wt0rzs.jpg",
      name: "NOTEBOOK LENOVO IDEAPAD 3 I3 10MA GEN 8GB 512GB SSD 15.6 W10H",
      brand: "Lenovo",
      detail: [
        "Procesador: Intel Core i3-10110U",
        "Tarjeta de video: Intel UHD Graphics",
        "Frecuencia: 2.1 GHz (hasta 4.1 GHz)",
        "Memoria ram: 8GB DDR4 (2666 MHz)",
        "Almacenamiento: SSD 512GB",
        "Resolución: Full HD 1920x1080",
        "Tamaño: 15.6",
      ],
      price: 559.0,
      category: "Notebooks",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238635/ecommerce/61_CtxUGH7L._AC_SL1000__jzcctp.jpg",
      name: "NOTEBOOK ASUS TUF GAMING FX505DY-AL117T",
      brand: "Asus",
      detail: [
        "Procesador: AMD Ryzen 5 3550H",
        "Tarjeta de video: AMD Radeon RX 560X 4GB",
        "Frecuencia: 2.1 GHz (hasta 3.7 GHz)",
        "Memoria ram: 8GB DDR4 (2400 MHz)",
        "Almacenamiento: HDD 1TB",
        "Resolución: Full HD 1920x1080 (120 Hz)",
        "Tamaño: 15.6",
      ],
      price: 849.0,
      category: "Notebooks",
      stock: 6,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683238649/ecommerce/81KyhfcoB4L_naknqz.jpg",
      name: "HP Pavilion Gaming Laptop",
      brand: "HP",
      detail: [
        "Procesador: AMD Ryzen 5 5600H",
        "Tarjeta de video: NVIDIA GeForce GTX 1650 4GB GDDR6",
        "Frecuencia: 3.3 GHz",
        "Memoria ram: 8GB DDR4-3200 SDRAM",
        "Almacenamiento: 512 GB PCIe NVMe SSD",
        "Resolución: 1920 x 1080",
        "Tamaño: 15.6",
      ],
      price: 799.99,
      category: "Notebooks",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241199/ecommerce/71cZbipx6wS._AC_SX466__ibyboe.jpg",
      name: "Microsoft Surface Laptop 4",
      brand: "Microsoft",
      detail: [
        "Procesador: Intel Core i5-1135G7",
        "Tarjeta de video: Intel Iris Xe Graphics",
        "Frecuencia: 4.2 GHz",
        "Memoria ram: 8GB LPDDR4x",
        "Almacenamiento: 256GB SSD",
        "Resolución: 2256 x 1504",
        "Tamaño: 13.5",
      ],
      price: 1299.99,
      category: "Notebooks",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241221/ecommerce/71UHz5MDgQL._AC_SL1500__sloj67.jpg",
      name: "ASUS ROG Zephyrus G14",
      brand: "ASUS",
      detail: [
        "Procesador: AMD Ryzen 9 5900HS",
        "Tarjeta de video: NVIDIA GeForce RTX 3060 Max-Q 6GB GDDR6",
        "Frecuencia: 3.3 GHz",
        "Memoria ram: 16GB DDR4-3200 SDRAM",
        "Almacenamiento: 1TB PCIe NVMe M.2 SSD",
        "Resolución: 2560 x 1440",
        "Tamaño: 14",
      ],
      price: 1999.99,
      category: "Notebooks",
      stock: 3,
      delete: false,
    },
    {
      //1
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241241/ecommerce/81v9NoiRjBL_okukc8.jpg",
      name: "PLACA DE VIDEO RTX 2060 EVGA SC GAMING 6GB",
      brand: "Nvidia",
      detail: [
        "Memoria: 6144 MB, 192 bit GDDR6, 14000 MHz ",
        "Interfaz: PCIe 3.0 16x, DVI-D, HDMI, DisplayPort",
        "Soporte de Sistema Operativo: Windows 10 64bit, Windows 7 64bit",
        "Max Digital : 7680x4320",
        "1755 MHz Boost Clock",
      ],
      price: 1999.99,
      category: "Placas de video",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241259/ecommerce/719dUNo9gDS._AC_SX522__fpe0wj.jpg",
      name: "ASUS TUF Gaming NVIDIA GeForce RTX 3060",
      brand: "Nvidia",
      detail: [
        "Memoria: 12 GB, 192 bit GDDR6, 15000 MHz ",
        "Interfaz: PCIe 4.0 16x, HDMI, DisplayPort",
        "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
        "Max Digital : 7680x4320",
        "Boost Clock: 1777 MHz",
      ],
      price: 2799.99,
      category: "Placas de video",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241280/ecommerce/concepto-6449140_tszmpl.jpg",
      name: "Gigabyte Radeon RX 6600 XT GAMING OC 8GB",
      brand: "AMD",
      detail: [
        "Memoria: 8 GB, 128 bit GDDR6, 16000 MHz",
        "Interfaz: PCIe 4.0 16x, HDMI 2.1, DisplayPort 1.4a",
        "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
        "Max Digital : 7680x4320",
        "Boost Clock: 2589 MHz",
      ],
      price: 2399.99,
      category: "Placas de video",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241298/ecommerce/51PoGBuf0nL._AC__kkhclb.jpg",
      name: "Sapphire Radeon RX 6900 XT Nitro+",
      brand: "AMD",
      detail: [
        "Memoria: 16 GB, 256 bit GDDR6, 16000 MHz",
        "Interfaz: PCIe 4.0 16x, HDMI 2.1, DisplayPort 1.4",
        "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
        "Max Digital: 7680x4320",
        "Boost Clock: 2365 MHz",
      ],
      price: 3999.99,
      category: "Placas de video",
      stock: 1,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241332/ecommerce/concepto-5400681_mblgbo.jpg",
      name: "ASUS ROG Strix NVIDIA GeForce RTX 3090",
      brand: "Nvidia",
      detail: [
        "Memoria: 24 GB, 384 bit GDDR6X, 19500 MHz",
        "Interfaz: PCIe 4.0 16x, HDMI 2.1, DisplayPort 1.4a",
        "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
        "Max Digital: 7680x4320",
        "Boost Clock: 1860 MHz",
      ],
      price: 5999.99,
      category: "Placas de video",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683296050/81gN7myaekL._AC_SX450__wgu1ds.jpg",
      name: "MSI Gaming GeForce GTX 1660 Super",
      brand: "Nvidia",
      detail: [
        "Memoria: 6 GB, 192 bit GDDR6, 14000 MHz",
        "Interfaz: PCIe 3.0 16x, HDMI, DisplayPort, DVI-D",
        "Soporte de Sistema Operativo: Windows 10 64bit, Windows 7 64bit",
        "Max Digital: 7680x4320",
        "Boost Clock: 1830 MHz",
      ],
      price: 1499.99,
      category: "Placas de video",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241346/ecommerce/20180717145208_25354_72_1_ibl5p8.jpg",
      name: "Gigabyte AORUS GeForce GTX 1080 Ti Xtreme Edition 11GB",
      brand: "Nvidia",
      detail: [
        "Memoria: 11 GB, 352 bit GDDR5X, 11010 MHz",
        "Interfaz: PCIe 3.0 16x, HDMI, DisplayPort, DVI-D",
        "Soporte de Sistema Operativo: Windows 10 64bit, Windows 7 64bit",
        "Max Digital: 7680x4320",
        "Boost Clock: 1746 MHz",
      ],
      price: 2999.99,
      category: "Placas de video",
      stock: 1,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241359/ecommerce/asus-rtx-3060-ti-oc-dual-fan-dual-rtx3060ti-o8gd6x-tarjeta-de-video-caja_vudbjq.jpg",
      name: "ASUS TUF Gaming NVIDIA GeForce RTX 3060 Ti",
      brand: "Nvidia",
      detail: [
        "Memoria: 8 GB, 256 bit GDDR6, 14000 MHz",
        "Interfaz: PCIe 4.0 16x, HDMI 2.1, DisplayPort 1.4a",
        "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
        "Max Digital: 7680x4320",
        "Boost Clock: 1665 MHz",
      ],
      price: 2499.99,
      category: "Placas de video",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241372/ecommerce/40847_1_i9q5rx.jpg",
      name: "Gigabyte GeForce GT 1030",
      brand: "Nvidia",
      detail: [
        "Memoria: 2 GB, 64 bit GDDR5, 6008 MHz",
        "Interfaz: PCIe 3.0 16x, HDMI 2.0b, DisplayPort 1.4",
        "Soporte de Sistema Operativo: Windows 10 64bit, Windows 7 64bit",
        "Max Digital: 4096x2160",
        "Boost Clock: 1518 MHz",
      ],
      price: 599.99,
      category: "Placas de video",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241385/ecommerce/51veSCNgo7L._AC_SX569__okhr3l.jpg",
      name: "Gigabyte Radeon RX 6600 XT GAMING OC 8GB",
      brand: "AMD",
      detail: [
        "Memoria: 8 GB, 192 bit GDDR5, 8002 MHz",
        "Interfaz: PCIe 3.0 16x, HDMI, DisplayPort, DVI-D",
        "Soporte de Sistema Operativo: Windows 10 64bit, Windows 7 64bit",
        "Max Digital: 7680x4320",
        "Boost Clock: 1830 MHz",
      ],
      price: 1599.99,
      category: "Placas de video",
      stock: 4,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241399/ecommerce/gaming-shop-canada-246057_1024x-min_m57pcp.png",
      name: "PLAYSTATION PS5",
      brand: "Sony",
      detail: [
        "Accesorios incluidos: 1 soporte vertical,1 cable de alimentación AC,1 cable USB,1 cable HDMI,1 manual",
        "Edición: Standard",
        "Altura: 104 mm",
        "Profundidad: 260 mm",
        "Resolución máxima de salida de video: 7680 px x 4320 px",
        "Velocidad del procesador: 3.5 GHz",
      ],
      price: 1599.99,
      category: "Consolas",
      stock: 4,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241426/ecommerce/D_NQ_NP_963862-MLA45041918050_032021-O_cqxizn.jpg",
      name: "Xbox Series X",
      brand: "Microsoft",
      detail: [
        "Accesorios incluidos: 1 control inalámbrico Xbox Series X,1 cable de alimentación AC,1 cable HDMI de alta velocidad,1 manual",
        "Edición: Standard",
        "Altura: 151 mm",
        "Profundidad: 151 mm",
        "Resolución máxima de salida de video: 8K",
        "Velocidad del procesador: 3.8 GHz",
      ],
      price: 1499.99,
      category: "Consolas",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241444/ecommerce/71qccaRKQVL_prsnpy.jpg",
      name: "Nintendo Switch",
      brand: "Nintendo",
      detail: [
        "Accesorios incluidos: 1 base de Nintendo Switch,1 control Joy-Con izquierdo,1 control Joy-Con derecho,1 par de agarres para control Joy-Con,1 soporte Joy-Con,1 cable HDMI,1 adaptador de corriente AC",
        "Edición: Standard",
        "Altura: 102 mm",
        "Profundidad: 239 mm",
        "Resolución máxima de salida de video: 1920 px x 1080 px",
        "Velocidad del procesador: 1.02 GHz",
      ],
      price: 399.99,
      category: "Consolas",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683252873/SEGA-Mega-Drive-Mini-2_jeiar8.jpg",
      name: "Sega Genesis Mini",
      brand: "Sega",
      detail: [
        "Accesorios incluidos: 2 controles con cable,1 cable de alimentación AC,1 cable HDMI",
        "Edición: Standard",
        "Altura: 45 mm",
        "Profundidad: 133 mm",
        "Resolución máxima de salida de video: 720 px x 480 px",
        "Velocidad del procesador: 533 MHz",
      ],
      price: 79.99,
      category: "Consolas",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241475/ecommerce/playstation-one-original_f2b2_zym9sb.jpg",
      name: "PlayStation 1",
      brand: "Sony",
      detail: [
        "Accesorios incluidos: 1 control DualShock, cable de alimentación, cable AV",
        "Altura: 77 mm",
        "Ancho: 260 mm",
        "Profundidad: 185 mm",
        "Resolución máxima de salida de video: 480i",
        "Velocidad del procesador: 33.8 MHz",
      ],
      price: 99.99,
      category: "Consolas",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683241488/ecommerce/dbaccc62-1405-45c3-a9e0-82eee8b1039d_1.ccbb04536b1daeab75e8248b0a1ac1e6_wfwgjg.jpg",
      name: "PlayStation 2",
      brand: "Sony",
      detail: [
        "Accesorios incluidos: 1 control DualShock 2, cable de alimentación, cable AV",
        "Altura: 79 mm",
        "Ancho: 301 mm",
        "Profundidad: 182 mm",
        "Resolución máxima de salida de video: 1080i",
        "Velocidad del procesador: 294.9 MHz",
      ],
      price: 149.99,
      category: "Consolas",
      stock: 4,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683242168/ecommerce/ogy4s7ghdd3wympsyvtr.jpg",
      name: "Xbox 360",
      brand: "Microsoft",
      detail: [
        "Accesorios incluidos: 1 control inalámbrico Xbox 360, cable de alimentación, cable AV",
        "Altura: 83 mm",
        "Ancho: 309 mm",
        "Profundidad: 258 mm",
        "Resolución máxima de salida de video: 1080p",
        "Velocidad del procesador: 3.2 GHz",
      ],
      price: 199.99,
      category: "Consolas",
      stock: 6,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683242217/RUQO33I3ZVHRBIHS7V5HMHLYL4_zeycp6.jpg",
      name: "Nintendo Wii",
      brand: "Nintendo",
      detail: [
        "Accesorios incluidos: 1 control Wii Remote, 1 nunchuck, cable de alimentación, cable AV",
        "Altura: 44 mm",
        "Ancho: 215.4 mm",
        "Profundidad: 157 mm",
        "Resolución máxima de salida de video: 480p",
        "Velocidad del procesador: 729 MHz",
      ],
      price: 129.99,
      category: "Consolas",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683242515/147-1478452_playstation-3-ps3-slim_zyqafs.jpg",
      name: "PlayStation 3",
      brand: "Sony",
      detail: [
        "Accesorios incluidos: 1 control DualShock 3, cable de alimentación, cable HDMI",
        "Altura: 98 mm",
        "Ancho: 290 mm",
        "Profundidad: 290 mm",
        "Resolución máxima de salida de video: 1080p",
        "Velocidad del procesador: 3.2 GHz",
      ],
      price: 249.99,
      category: "Consolas",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683242560/1280px-Microsoft-Xbox-One-S-Console-wController-L_tbios2.jpg",
      name: "Xbox One",
      brand: "Microsoft",
      detail: [
        "Accesorios incluidos: 1 control inalámbrico Xbox One, cable de alimentación, cable HDMI",
        "Altura: 79 mm",
        "Ancho: 333 mm",
        "Profundidad: 276 mm",
        "Resolución máxima de salida de video: 1080p",
        "Velocidad del procesador: 1.75 GHz",
      ],
      price: 299.99,
      category: "Consolas",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683242746/10164813037618_fqhikw.jpg",
      name: "FUENTE AEROCOOL DORADO 650W 80 PLUS GOLD",
      brand: "Aerocool",
      detail: [
        "Certificación 80Plus Gold para hasta un 92% + de eficiencia",
        "Compatible con tarjetas madre RGB direccionables a través de conector ARGB",
        "El ventilador de alta presión de 12 cm con velocidad optimizada permite un ruido del ventilador casi inaudible y un funcionamiento silencioso de la fuente de alimentación",
        "Con un diseño elegante con ventilador ARGB de 12 cm",
        "Tamaño: 140 mm (W) x 150 mm (L) x 86 mm (H)",
      ],
      price: 299.99,
      category: "Fuentes",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683242765/41CeZQLDl-S._AC__wbdild.jpg",
      name: "Corsair CX550M",
      brand: "Corsair",
      detail: [
        "Certificación 80 Plus Bronze para hasta un 88% de eficiencia",
        "Ventilador de 120 mm con control térmico que ajusta automáticamente la velocidad del ventilador para reducir el ruido",
        "Compatibilidad total con los sistemas de PC modernos",
        "Dimensiones: 140 mm (An) x 150 mm (L) x 86 mm (Al)",
        "Cables completamente modulares para una fácil instalación y una apariencia ordenada",
      ],
      price: 79.99,
      category: "Fuentes",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243366/1581704574_600br_ona1yu.jpg",
      name: "EVGA 600 BR",
      brand: "EVGA",
      detail: [
        "Certificación 80 Plus Bronze para hasta un 85% de eficiencia",
        "Ventilador de 120 mm de alta calidad para un enfriamiento eficiente y un bajo nivel de ruido",
        "Protecciones completas para mayor seguridad y fiabilidad",
        "Dimensiones: 85 mm (An) x 140 mm (L) x 150 mm (Al)",
        "Cables fijos para una instalación sencilla",
      ],
      price: 64.99,
      category: "Fuentes",
      stock: 12,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243379/SPD-0500P_Foto0g_vjnltr.jpg",
      name: "Thermaltake Smart 500W",
      brand: "Thermaltake",
      detail: [
        "Certificación 80 Plus White para hasta un 80% de eficiencia",
        "Ventilador de 120 mm con control térmico para un enfriamiento eficiente y un bajo nivel de ruido",
        "Diseño de cable plano para un manejo sencillo de los cables y una mejor circulación de aire",
        "Dimensiones: 150 mm (An) x 86 mm (L) x 140 mm (Al)",
        "Cables fijos para una fácil instalación",
      ],
      price: 54.99,
      category: "Fuentes",
      stock: 20,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243403/fuente-650w-corsair-cx650m-80-plus-bronze-semi-modular-0_ib2x9y.jpg",
      name: "Corsair CX650M",
      brand: "Corsair",
      detail: [
        "Certificación 80 Plus Bronze para hasta un 88% de eficiencia",
        "Ventilador de 120 mm con control térmico que ajusta automáticamente la velocidad del ventilador para reducir el ruido",
        "Compatibilidad total con los sistemas de PC modernos",
        "Dimensiones: 140 mm (An) x 150 mm (L) x 86 mm (Al)",
        "Cables completamente modulares para una fácil instalación y una apariencia ordenada",
      ],
      price: 79.99,
      category: "Fuentes",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243415/61z1DxTOVaL_jrrsga.jpg",
      name: "Cooler Master MWE 650 White V2",
      brand: "Cooler Master",
      detail: [
        "Certificación 80 Plus White para una eficiencia energética del 80%",
        "Ventilador de 120 mm con control de velocidad inteligente",
        "Totalmente modular, con cables planos para una gestión de cables fácil y ordenada",
        "Iluminación RGB direccionable en el ventilador y en el logotipo de Cooler Master",
        "Dimensiones: 150 mm (An) x 140 mm (L) x 86 mm (Al)",
      ],
      price: 89.99,
      category: "Fuentes",
      stock: 6,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243431/51To6QUlUwL._AC__sbmcvp.jpg",
      name: "EVGA SuperNOVA 850 G5",
      brand: "EVGA",
      detail: [
        "Certificación 80 Plus Gold para una eficiencia energética del 90%",
        "Ventilador de 135 mm con control de velocidad inteligente",
        "Totalmente modular, con cables planos para una gestión de cables fácil y ordenada",
        "Iluminación RGB en la carcasa de la fuente",
        "Dimensiones: 150 mm (An) x 150 mm (L) x 86 mm (Al)",
      ],
      price: 159.99,
      category: "Fuentes",
      stock: 4,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243444/1019-producto-fuente-seasonic-focus-750w-gold-80-plus-2-3244-600x544_rtqgzd.jpg",
      name: "Seasonic FOCUS GX-750",
      brand: "Seasonic",
      detail: [
        "Certificación 80 Plus Gold para una eficiencia energética del 90%",
        "Ventilador de 120 mm con control de velocidad inteligente",
        "Totalmente modular, con cables planos para una gestión de cables fácil y ordenada",
        "Iluminación RGB direccionable en el ventilador",
        "Dimensiones: 140 mm (An) x 150 mm (L) x 86 mm (Al)",
      ],
      price: 129.99,
      category: "Fuentes",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243457/438fd795cbae58c9b6c9f10ed6570ec2_djpen4.jpg",
      name: "Aerocool mirage RGB 850W",
      brand: "Aerocool",
      detail: [
        "Certificación 80 Plus Gold para hasta un 90% de eficiencia",
        "Ventilador RGB de 120 mm con control térmico que ajusta automáticamente la velocidad del ventilador para reducir el ruido",
        "Completamente modular para una fácil instalación y una apariencia ordenada",
        "Capacitores japoneses de alta calidad para una entrega de energía confiable y estable",
        "Dimensiones: 140 mm (An) x 150 mm (L) x 86 mm (Al)",
      ],
      price: 129.99,
      category: "Fuentes",
      stock: 5,
      delete: false,
    },
    {
      image:
        "https://res.cloudinary.com/dezvujzed/image/upload/v1683243468/71B-dP3uO8L._AC_SX679__v0o3g7.jpg",
      name: "Thermaltake Toughpower GF1 850W",
      brand: "Thermaltake",
      detail: [
        "Certificación 80 Plus Gold para hasta un 90% de eficiencia",
        "Ventilador RGB de 140 mm con control térmico que ajusta automáticamente la velocidad del ventilador para reducir el ruido",
        "Completamente modular para una fácil instalación y una apariencia ordenada",
        "Capacitores japoneses de alta calidad para una entrega de energía confiable y estable",
        "Dimensiones: 150 mm (An) x 160 mm (L) x 86 mm (Al)",
      ],
      price: 149.99,
      category: "Fuentes",
      stock: 3,
      delete: false,
    },
  ],
};
