const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
const ORDER_BY = 'ORDER_BY';
const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
const FILTER_BY_BRAND = 'FILTER_BY_BRAND';