export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const ORDER_BY = 'ORDER_BY';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ALL = 'REGISTER_ALL'
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'



