module.exports = {
  motherboards: [
    {
      image:
        "https://img.pccomponentes.com/articles/1059/10594876/1607-asus-rog-strix-b650e-f-gaming-wifi.jpg",
      name: "MOTHER ASUS (AM5) ROG STRIX B650E-E GAMING WFI",
      brand: "Asus",
      detail: [
        "AMD Socket AM5 for AMD Ryzen 7000 Series Desktop Processors",
        "Total supports 4 x M.2 slots and 4 x SATA 6Gb/s ports",
        "ROG SupremeFX 7.1 Surround Sound High Definition Audio CODEC ALC4080",
        "4x DIMM Slots, DDR5 6400MHz, PCIe Gen 5, 4x SATA 6Gb/s connectors, 4xM.2 Slot, 2.5GB LAN",
        "Graphics: 1 x DisplayPort* 1 x HDMI® port",
        "Expansion Slots AMD Ryzen™ 7000 Series Desktop Processors*",
      ],
      price: 217.453,
      category: "Motherboard",
      stock: 0,
      delete: false,
    },
    {
      image:
        "https://static.nb.com.ar/i/nb_MOTHER-ASUS-(1151)-PRIME-Z390-A_ver_231548eadd0a241bd1301b9b1f8c4c11.jpeg",
      name: "ASUS Prime Z390-A Motherboard",
      brand: "Asus",
      detail: [
        "Intel LGA 1151 socket",
        "DDR4 memory compatibility",
        "Dual M.2, Gigabit LAN, and USB 3.1 Gen 2",
        "OptiMem II technology for stability and improved DDR4 overclocking",
        "Fan Xpert 4 for advanced fan and liquid cooling controls",
      ],
      price: 189.99,
      category: "Motherboard",
      stock: 5,
      delete: false,
    },
    {
      image: "https://www.computerevolution.com.co/wp-content/uploads/450.png",
      name: "Gigabyte B450M DS3H",
      brand: "Gigabyte",
      detail: [
        "AMD Ryzen AM4 socket",
        "Dual Channel DDR4, 4 DIMMs",
        "PCIe Gen3 M.2 NVMe with thermal guard",
        "High-quality Audio Capacitors and Audio Noise Guard with LED Trace Path Lighting",
        "RGB Fusion supports RGB LED strips in 7 colors",
        "Smart Fan 5 with Fan Stop for silent cooling",
      ],
      price: 72.99,
      category: "Motherboard",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://m.media-amazon.com/images/I/71tT8kkyCzL._AC_UF894,1000_QL80_.jpg",
      name: "ASRock H310CM-HDV LGA1151/Intel H310/DDR4/SATA3&USB3.1",
      brand: "ASRock",
      detail: [
        "Intel LGA 1151 socket",
        "DDR4 memory compatibility",
        "M.2 for SSDs",
        "Realtek Gigabit LAN",
        "5X Protection II for hardware-level safeguards",
      ],
      price: 68.99,
      category: "Motherboard",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://http2.mlstatic.com/D_NQ_NP_988107-MLA47192040205_082021-O.jpg",
      name: "MSI MPG Z590 Gaming Edge WiFi ATX Gaming Motherboard",
      brand: "MSI",
      detail: [
        "Supports 11th and 10th Gen Intel Core/Pentium/Celeron processors",
        "DDR4 Memory, up to 5333 MHz",
        "Lightning-fast experience: PCIe 4.0, Lightning Gen 4 M.2",
        "Wi-Fi 6E ready: 6GHz band provides the next level of Wi-Fi",
      ],
      price: 68.99,
      category: "Motherboard",
      stock: 10,
      delete: false,
    },
    {
      image:
        "https://app.contabilium.com/files/explorer/16752/Productos-Servicios/concepto-4786979.jpg",
      name: "ASUS ROG MAXIMUS XIII HERO",
      brand: "Asus",
      detail: [
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-5333 MHz (OC)",
        "2.5 Gbps Ethernet, Wi-Fi 6E, Bluetooth 5.2",
        "USB 3.2 Gen 2x2 front panel connector, Thunderbolt 4 support",
        "5-Way Optimization, AI Overclocking, and AI Cooling",
        "Integrated I/O shield and Aura Sync RGB lighting",
      ],
      price: 599.99,
      category: "Motherboard",
      stock: 5,
      delete: false,
    },
    {
     
      image:
        "https://images-eu.ssl-images-amazon.com/images/I/81IPvOEkCqS._AC_UL600_SR600,600_.jpg",
      name: "GIGABYTE AORUS X570 MASTER",
      brand: "Gigabyte",
      detail: [
        "AMD X570 Chipset",
        "AMD AM4 Socket",
        "4 x DIMM DDR4-4400 MHz (OC)",
        "Intel WiFi 6 802.11ax, Bluetooth 5.0",
        "2.5 GbE LAN, ALC1220-VB Audio Codec, ESS SABRE HiFi 9118 DAC",
        "12+2 Phases IR Digital VRM Solution with PowIRstage",
      ],
      price: 359.99,
      category: "Motherboard",
      stock: 2,
      delete: false,
    },
    {
      image:
        "https://http2.mlstatic.com/D_NQ_NP_714975-MLA48394174068_112021-O.jpg",
      name: "ASROCK B560M STEEL LEGEND",
      brand: "ASRock",
      detail: [
        "Intel B560 Chipset",
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-5000 MHz (OC)",
        "2.5 GbE LAN, Intel Wi-Fi 6E",
        "USB 3.2 Gen 2x2 Type-C, Thunderbolt 4 support",
        "Steel Legend Armor and RGB Lighting",
      ],
      price: 144.99,
      category: "Motherboard",
      stock: 8,
      delete: false,
    },
    {
      image:
        "https://media.solotodo.com/media/products/1153285_picture_1589638721.jpg",
      name: "ASUS ROG STRIX Z490-E GAMING",
      brand: "Asus",
      detail: [
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-4600 MHz (OC)",
        "2.5 Gbps Ethernet, Wi-Fi 6, Bluetooth 5.1",
        "USB 3.2 Gen 2x2 Type-C, Thunderbolt 3 support",
        "ROG SupremeFX ALC1220A Audio Codec",
        "Pre-mounted I/O shield and Aura Sync RGB lighting",
      ],
      price: 349.99,
      category: "Motherboard",
      stock: 3,
      delete: false,
    },
    {
      image:
        "https://image.ceneostatic.pl/data/products/103702104/i-gigabyte-z590-aorus-master.jpg",
      name: "GIGABYTE Z590 AORUS MASTER",
      brand: "Gigabyte",
      detail: [
        "Intel LGA 1200 Socket",
        "4 x DIMM DDR4-5400 MHz (OC)",
        "Intel 2.5 GbE LAN, Wi-Fi 6E, Bluetooth 5.2",
        "USB 3.2 Gen 2x2 Type-C, Thunderbolt 4 support",
        "ALC1220-VB Audio Codec, ESS SABRE HiFi 9118 DAC",
        "Advanced Thermal Design with Fins-Array II, Direct Touch Heatpipe II, and Nanocarbon Coating",
      ],
      price: 549.99,
      category: "Motherboard",
      stock: 4,
      delete: false,
    },
  ],
  monitores: [
    {
   
      image:
        "https://www.lg.com/cac/images/monitores/md06141916/gallery/N01_M-01.jpg",
      name: "LG 27'27GL650F G",
      brand: "LG",
      detail: [
        "G-Sync Compatible certificado por NVIDIA",
        "Tamaño (pulgada) 27 pulgadasTalla (cm): 68.5cm",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 5 ms (GtG a mayor velocidad), 1 ms MBR",
        "Tratamiento de superficies: Antirreflejo, 25% 3H.",
      ],
      price: 19.99,
      category: "Monitores",
      stock: 4,
      delete: false,
    },
    {
  
      image:
        "https://bdhard.com.ar/wp-content/uploads/2022/10/monitor-gamer-144hz-viewsonic_42603_1.jpeg",
      name: "ViewSonic VX2768-2KPC-MHD",
      brand: "ViewSonic",
      detail: [
        "Tamaño de pantalla: 27 pulgadas (27 pulgadas / 68,47 cm visible)",
        "Resolución: WQHD (2560 x 1440)",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "Tecnología AMD FreeSync",
      ],
      price: 279.99,
      category: "Monitores",
      stock: 6,
      delete: false,
    },
    {
     
      image: "https://www.displaydb.com/assets/images/700/dell-s2719dgf.jpg",
      name: "Dell S2719DGF",
      brand: "Dell",
      detail: [
        "Tamaño de pantalla: 27 pulgadas",
        "Resolución: QHD (2560 x 1440)",
        "Tipo de panel: TN",
        "Tiempo de respuesta: 1 ms",
        "Frecuencia de actualización: 155Hz",
        "Tecnología AMD FreeSync 2 HDR",
      ],
      price: 319.99,
      category: "Monitores",
      stock: 2,
      delete: false,
    },
    {
   
      image: "https://m.media-amazon.com/images/I/813CwWhZNXL._AC_SL1500_.jpg",
      name: "ASUS TUF Gaming VG249Q",
      brand: "ASUS",
      detail: [
        "Tamaño (pulgada) 23,8 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "Altavoces estéreo integrados",
      ],
      price: 269.99,
      category: "Monitores",
      stock: 8,
      delete: false,
    },
    {
    
      image: "https://m.media-amazon.com/images/I/81iblFKwkeL.jpg",
      name: "AOC 27G2",
      brand: "AOC",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "Altavoces estéreo integrados",
      ],
      price: 249.99,
      category: "Monitores",
      stock: 12,
      delete: false,
    },
    {
  
      image:
        "https://http2.mlstatic.com/D_NQ_NP_978132-MLA42884863459_072020-O.jpg",
      name: "Samsung C27F398",
      brand: "Samsung",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: VA",
        "Tiempo de respuesta: 4 ms (GtG)",
        "Frecuencia de actualización: 60Hz",
        "Curvatura de pantalla 1800R",
      ],
      price: 229.99,
      category: "Monitores",
      stock: 6,
      delete: false,
    },
    {
     
      image:
        "https://www.arrichetta.com.ar/wp-content/uploads/2020/04/20190228162437_20694_235_1.jpg",
      name: "Dell Ultrasharp U2415",
      brand: "Dell",
      detail: [
        "Tamaño (pulgada) 24 pulgadas",
        "Resolución: 1920 x 1200",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 6 ms (GtG)",
        "Frecuencia de actualización: 60Hz",
        "Relación de aspecto 16:10",
      ],
      price: 249.99,
      category: "Monitores",
      stock: 10,
      delete: false,
    },
    {
  
      image:
        "https://media.ldlc.com/r1600/ld/products/00/05/49/56/LD0005495657_2.jpg",
      name: "Acer Nitro XV272U",
      brand: "Acer",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 2560 x 1440",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (VRB)",
        "Frecuencia de actualización: 144Hz",
        "HDR10",
      ],
      price: 399.99,
      category: "Monitores",
      stock: 5,
      delete: false,
    },
    {
 
      image: "https://image.coolblue.nl/600x315/products/1490628",
      name: "HP EliteDisplay E273",
      brand: "HP",
      detail: [
        "Tamaño (pulgada) 27 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 5 ms (GtG)",
        "Frecuencia de actualización: 60Hz",
        "Inclinación, pivote, rotación y ajuste de altura",
      ],
      price: 279.99,
      category: "Monitores",
      stock: 7,
      delete: false,
    },
    {

      image:
        "https://www.venex.com.ar/products_images/1614968556_dfghsdfhsdf.png",
      name: "ViewSonic XG2405",
      brand: "ViewSonic",
      detail: [
        "Tamaño (pulgada) 24 pulgadas",
        "Resolución: 1920 x 1080",
        "Tipo de panel: IPS",
        "Tiempo de respuesta: 1 ms (MPRT)",
        "Frecuencia de actualización: 144Hz",
        "FreeSync Premium",
      ],
      price: 189.99,
      category: "Monitores",
      stock: 9,
      delete: false,
    },
  ]
};
